### ISSUE TITLE
redis操作报错

### ISSUE THREAD

**Issue by Andy5972** [sairson/Yasso#13]
Yasso_win_x64.exe crack redis --rebound 127.0.0.1:6379 --pass 12345678 --port 6379 --hostname 127.0.0.1
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
Yasso/cmd.RedisInfo(0xb10040, 0xc000006620, 0xc000023808, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        F:/tools/Yasso/cmd/redis.go:179 +0x645
Yasso/cmd.RedisAuthConn(0xc000022280, 0x9, 0x18eb, 0x0, 0x0, 0x3b9aca00, 0x0, 0x0, 0x0, 0x0, ...)
        F:/tools/Yasso/cmd/redis.go:122 +0x3a5
Yasso/cmd.BruteRedisByUser()
        F:/tools/Yasso/cmd/redis.go:69 +0x11b
Yasso/cmd.glob..func13(0x10dbb80, 0xc000128780, 0x0, 0x8)
        F:/tools/Yasso/cmd/redis.go:23 +0x3d
github.com/spf13/cobra.(*Command).execute(0x10dbb80, 0xc000128700, 0x8, 0x8, 0x10dbb80, 0xc000128700)
        C:/Users/Administrator/go/go1.16.4/bin/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x10dbe00, 0x0, 0xc000049f78, 0xc000123f78)
        C:/Users/Administrator/go/go1.16.4/bin/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/Administrator/go/go1.16.4/bin/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
Yasso/cmd.Execute()
        F:/tools/Yasso/cmd/root.go:38 +0x38
main.main()
        F:/tools/Yasso/main.go:12 +0x27

**Comment by sairson** [comment]
我知道这个问题，你使用的应该是之前编译的版本，它存在redis的解析错误。我已经在源代码中修复了这个问题。但是并没有发布较新的版本。如果可以，你可以自行git下来进行编译

**Comment by Andy5972** [comment]
能更新个二进制包吗
