### ISSUE TITLE
苹果版本无法运行成功

### ISSUE THREAD

**Issue by Asura88** [sairson/Yasso#2]
苹果版本运行后不是一秒结束就是无任何反应。

![image](https://user-images.githubusercontent.com/25000885/148645515-7f1fd544-9b3f-422b-a17c-278189661420.png)

**Comment by Asura88** [comment]
顺便说一下，我改了一下文件名，莫非有关系？

**Comment by sairson** [comment]
这与名称应该无关，因为我是windows平台编写，测试均在windows平台，由于go语言编写的，具有跨平台性，mac和linux均是在朋友的macbook pro上编译，所以我不清楚发生了什么，我去跟我的小伙伴商讨下，看看是否能重现你的问题。感谢师傅的issue

**Comment by sairson** [comment]
我重现了你的问题，在linux和windows均正常，目前正在修复mac上的问题，谢谢

**Comment by sairson** [comment]
目前已经修复了，下载v0.0.4测试，谢谢师傅
