### ISSUE TITLE
跟fscan差不多讷

### ISSUE THREAD

**Issue by LuoooB** [sairson/Yasso#3]
RT

**Comment by sairson** [comment]
Yasso可以算的上一个缝合怪，功能上的确差不多，因为功能上参考了fscan，和zscan这些，但是我加入了一些其他的东西，师傅可以试试哦

**Comment by LuoooB** [comment]
占个坑

**Comment by sairson** [comment]
我自己觉得，这款工具的主要特色就在于强大的爆破和利用模块，特别是mssql的利用，加入了WarSQLKit的CLR，非常的强大了基本上

**Comment by sairson** [comment]
望师傅多多提建议哦
