### ISSUE TITLE
open log file failed open Yasso.log: too many open files

### ISSUE THREAD

**Issue by crypt0nX** [sairson/Yasso#5]
这个问题有影响吗
<img width="610" alt="WX20220113-095924@2x" src="https://user-images.githubusercontent.com/61395407/149252390-fa2dad15-4663-46d8-9412-7212d50eeed6.png">

**Comment by sairson** [comment]
这个会有点影响对于写日志，并且会退出程序。因为在本地，我没有遇到过这个，我会尽可能的修复这个问题，谢谢

**Comment by sairson** [comment]
我发现，出现那too many open files这个报错，似乎是linux服务器做了文件打开最大数量的限制，可以通过ulimit -a查看文件打开最大数量，并执行ulimit -n 2048似乎就可以解决

**Comment by crypt0nX** [comment]
> 测试了一下似乎没有问题了，谢谢师傅
