### ISSUE TITLE
当密码为空时，似乎仍然会跑完字典把结果打印出来

### ISSUE THREAD

**Issue by crypt0nX** [sairson/Yasso#6]
希望能修改一下
<img width="347" alt="WX20220115-162510@2x" src="https://user-images.githubusercontent.com/61395407/149615192-7b3549f3-08e9-43b4-bf70-5e71b395bbd5.png">

**Comment by sairson** [comment]
好的，我会尽快的去修改这个问题，谢谢师傅

**Comment by sairson** [comment]
源代码已经修复完毕，但是目前还未发布新版本，如需要可以自行下载编译。我会尽量发布最新版本，谢谢师傅的建议

**Comment by crypt0nX** [comment]
> 源代码已经修复完毕，但是目前还未发布新版本，如需要可以自行下载编译。我会尽量发布最新版本，谢谢师傅的建议
<img width="348" alt="WX20220117-150424@2x" src="https://user-images.githubusercontent.com/61395407/149722861-8d361c34-00ce-4ec5-a92b-108891142c12.png">
另外smb服务也有这个问题哈，麻烦修复一下
