### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by AkunWin** [sairson/Yasso#8]
爆破模块：指定的用户名不生效，爆破时还是会时用默认的

**Comment by sairson** [comment]
我回去尝试复现这个问题，请等待，谢谢提出

**Comment by sairson** [comment]
对了，你能具体指出是哪一个模块吗？非常感谢

**Comment by AkunWin** [comment]
> 对了，你能具体指出是哪一个模块吗？非常感谢

师傅，你好，目前我只测试了SSH爆破的模块

**Comment by sairson** [comment]
好的，我重现了这个问题，并且发现了一个新的问题，这是程序的bug，我会尽可能的修复。感谢

**Comment by AkunWin** [comment]
> 好的，我重现了这个问题，并且发现了一个新的问题，这是程序的bug，我会尽可能的修复。感谢

给大佬端茶

**Comment by sairson** [comment]
师傅有好的想法可以提，我会尽我最大的努力去实现它

**Comment by AkunWin** [comment]
OK，没问题~

**Comment by sairson** [comment]
师傅，你能提供一下你的使用命令吗？

**Comment by sairson** [comment]
我已经修复了在读取到空用户名密码时出现的panic错误，并且在本地测试成功使用字典的用户名密码进行了爆破

**Comment by sairson** [comment]
![image](https://user-images.githubusercontent.com/74412075/151141853-4da0d281-cf39-4944-a082-7e2333104054.png)

**Comment by AkunWin** [comment]
> 师傅，你能提供一下你的使用命令吗？

Yasso.exe crack ssh -H 127.0.0.1 --port 22 --user root --pd pwd.txt --crack

**Comment by AkunWin** [comment]
> ![image](https://user-images.githubusercontent.com/74412075/151141853-4da0d281-cf39-4944-a082-7e2333104054.png)

我就指定了一个用户，没有用用户名字典

**Comment by sairson** [comment]
目前还不支持指定当用户，这可能就是在使用时出现的问题，我会尽可能的加上这个方式

**Comment by sairson** [comment]
感谢哦，也通过测试时发现了一个使用bug，我已经完善了它、我会增加你需要的方式

**Comment by AkunWin** [comment]
> 目前还不支持指定当用户，这可能就是在使用时出现的问题，我会尽可能的加上这个方式

好的，我明白了，感谢师傅~

**Comment by sairson** [comment]
![image](https://user-images.githubusercontent.com/74412075/151143569-70e89f33-ea86-4a8e-94a4-a888ee754c6f.png)
你觉得这种格式的支持可以吗

**Comment by sairson** [comment]
![image](https://user-images.githubusercontent.com/74412075/151143717-cdfb76c0-e69f-452d-9c6b-118082a5ea53.png)
我让其兼容了两种格式，按照，分割来获取用户指定的用户名密码

**Comment by AkunWin** [comment]
> 

这种也没毛病，可以的。不过user.txt里面只放一个单用户也是可以的。

**Comment by sairson** [comment]
这可以作为完善，来方便使用。我的目标是能更便利的辅助自检和渗透过程。如果这种格式可以帮助你，我会尽可能的完善的

**Comment by AkunWin** [comment]
> 这可以作为完善，来方便使用。我的目标是能更便利的辅助自检和渗透过程。如果这种格式可以帮助你，我会尽可能的完善的

感谢师傅，向您学习~
